// const ProductCategories = {babyFood: "Baby Foods",
// alcohol: "Alcoholic Beverages",
// beverages: "Beverages",
// breadsAndBakery: "Breads & Bakery",
// breakfastFoods: "Breakfast Foods",
// "Dairy, Eggs & Plant-Based Alternatives",
// "Deli & Prepared Foods",
// "Food & Beverage Gifts",
// "Fresh Flowers & Live Indoor Plants",
// "Fresh Meal Kits",
// "Frozen",
// "Home Brewing & Winemaking",
// "Meat & Seafood",
// "Meat Substitutes",
// "Pantry Staples",
// "Produce",
// "Snacks & Sweets"}
